# Generated by Django 4.0.3 on 2022-03-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('exam_score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
